micronaut:
  application:
    name: keyManager
datasources:
  default:
    url: jdbc:postgresql://localhost/pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    schema-generate: CREATE_DROP
    ##dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update